@startuml

Actividad "1" - "0" Reloj
Actividad "0..n" <--* "n " Proyecto
Actividad <|-- Proyecto : hereda
Actividad <|-- Tarea : hereda
Tarea "1" <-- "1..n" Intervalo : dependencia >
Actividad "0..n" -- "0..n" Tag

Abstract Actividad {
-actNombre
-actLdtFechaInicial
-actLdtFechaFinal
-actFechaInicial
-actFechaFinal
-actTiempoTotal
-actProyectoSuperior
-actClase
-actReloj
-logger

+actInvariant()
+getNombre()
+getFechaInicial()
+getFechaFinal()
+getTiempoTotal()
+getProyectoSuperior()
+setFechaInicial(start)
+setFechaFinal(finish)
+setTiempoTotal()
+setActReloj()
+searchFlag()
+actMostrar()
+getJson()
}

Abstract Proyecto {
-proListaTareas
-proListaProyectos

+anadirTarea(task)
+anadirProyecto(proyect)
+setTiempoTotal()
+searchFlag()
+getJson()
}

Class Tarea {
-tarListaIntervalos
-tarReloj

+tarInvariant()
+tarGetinstance()
+setTiempoTotal()
+searchFlag()
+anadirIntervalo(interval)
+start()
+stop()
+getJson()
}

Class Intervalo {
-intLdtFechaInicial
-intLdtFechaFinal
-intFechaInicial
-intFechaFinal
-intTiempoTotal
-intTareaSuperior
-intClase
-intflag
-logger

+intInvariant()
+intGetTiempoTotal()
+isIntflag()
+stopFlag()
+intSetFechaFinal(finish)
+intSetTiempoTotal()
+intMostrar()
+getJson()
+update()
}

Class Tag{
-tagList
-actList
-logger

+tagInvariant()
+anadirTag()
+searchTag()
}

Class Reloj {
-periodo
-uniqueinstance
-flag
-logger

+getInstance()
+changeFlag()
+notificar()
+run()
}

@enduml
